development:
 paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
 paypal_secret_id: <%= ENV["PAYPAL_SECRET_ID"] %>
test:

production:
 paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
 paypal_secret_id: <%= ENV["PAYPAL_SECRET_ID"] %>

